### ISSUE TITLE
send reset link button is not working #bug

### ISSUE THREAD

**Issue by vineel31** [CSC510-SE-Uddharsh-Vineel-Chandrakant/CSC510-WolfJobs-G50#1]
![image](https://github.com/user-attachments/assets/e84a7798-04f4-43d1-add1-d7ffc3823242)

**Comment by konetichandrakant** [comment]
Check the route in the backend located at /backend/routes/api/v1/users.js. The 404 error signifies that the page is not found, indicating a potential issue with the router.

**Comment by vineel31** [comment]
Yea checked the route, there was an error in it but i was able to resolve. Thank you
