### ISSUE TITLE
Not able to verify the token? it giving undefined!!!

### ISSUE THREAD

**Issue by vineel31** [CSC510-SE-Uddharsh-Vineel-Chandrakant/CSC510-WolfJobs-G50#3]
![image](https://github.com/user-attachments/assets/d0630f01-e112-404c-bbec-1e8c3756d95a)

**Comment by konetichandrakant** [comment]
Check your JWT secret is same for encoding and decoding. I think we can resolve this issue if we have same secret globally for entire project.

**Comment by vineel31** [comment]
yes, was able to resolve.
