### ISSUE TITLE
Should we opt ML approach for skills extraction / Hard coding by predicting skills and filtering?

### ISSUE THREAD

**Issue by konetichandrakant** [CSC510-SE-Uddharsh-Vineel-Chandrakant/CSC510-WolfJobs-G50#4]
1) ML approach:
a) This approach is better for dynamic cases and gives accurate output if we have well trained model.
b) It is not fast as hardcoding either in performance or in developing the feature

2) Hard Coding:
a) It is better for tasks where skills are already known
b) It is development friendly and better in performance

**Comment by vineel31** [comment]
As there are no proper models currently i think its better to go with hard coding of skills

**Comment by konetichandrakant** [comment]
Ok will try to collect repetivite skills from web and code accordingly.
